const state={cart:JSON.parse(localStorage.getItem("rxm_v2_cart")||"[]"),wish:JSON.parse(localStorage.getItem("rxm_v2_wish")||"[]"),category:"SEMUA",search:"",products:window.PRODUCTS||[],orderId:null,poll:null};
const $=s=>document.querySelector(s);
const money=n=>new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0}).format(n);
function save(){localStorage.setItem("rxm_v2_cart",JSON.stringify(state.cart));localStorage.setItem("rxm_v2_wish",JSON.stringify(state.wish));updateCounts();renderCart();}
function toast(m){const t=$("#toast");t.textContent=m;t.classList.add("show");clearTimeout(window.__toast);window.__toast=setTimeout(()=>t.classList.remove("show"),2300)}
function page(id){document.querySelectorAll(".page").forEach(x=>x.classList.remove("active"));$("#"+id).classList.add("active");window.scrollTo({top:0,behavior:"smooth"});if(id==="productsPage")renderProducts();if(id==="checkoutPage")renderCheckout();}
document.addEventListener("click",e=>{const p=e.target.closest("[data-page]");if(p)page(p.dataset.page+"Page");});
function renderNav(cats){$("#categoryNav").innerHTML=cats.map(c=>`<button class="${state.category===c?"active":""}" data-cat="${c}">${c}</button>`).join("");$("#filters").innerHTML=cats.map(c=>`<button class="filter ${state.category===c?"active":""}" data-cat="${c}">${c}</button>`).join("");document.querySelectorAll("[data-cat]").forEach(b=>b.onclick=()=>{state.category=b.dataset.cat;renderNav(cats);page("productsPage");});}
function card(p){const wished=state.wish.includes(p.id);return `<article class="product-card" data-id="${p.id}"><div class="visual"><span class="label">${p.badge}</span><button class="heart ${wished?"active":""}" data-wish="${p.id}">${wished?"♥":"♡"}</button><span class="visual-icon">${p.art}</span></div><div class="body"><div class="cat">${p.category}</div><div class="name">${p.name}</div><div class="meta">★ ${p.rating} • ${p.sold.toLocaleString("id-ID")} TERJUAL</div><div class="price"><strong>${money(p.price)}</strong><span class="old">${money(p.oldPrice)}</span></div><button class="add" data-add="${p.id}">+</button></div></article>`}
function filtered(){let x=state.products.filter(p=>(state.category==="SEMUA"||p.category===state.category)&&(!state.search||`${p.name} ${p.category}`.toLowerCase().includes(state.search)));const s=$("#sortSelect")?.value||"popular";if(s==="low")x.sort((a,b)=>a.price-b.price);if(s==="high")x.sort((a,b)=>b.price-a.price);if(s==="az")x.sort((a,b)=>a.name.localeCompare(b.name));if(s==="popular")x.sort((a,b)=>b.sold-a.sold);return x}
function renderProducts(){const x=filtered();$("#productsGrid").innerHTML=x.length?x.map(card).join(""):`<div class="form-card" style="grid-column:1/-1;text-align:center">PRODUK TIDAK DITEMUKAN</div>`;$("#resultText").textContent=`${x.length} PRODUK TERSEDIA`}
function renderHome(){const x=[...state.products].sort((a,b)=>b.sold-a.sold).slice(0,10);$("#featuredGrid").innerHTML=x.map(card).join("")}
function updateCounts(){const n=state.cart.reduce((s,x)=>s+x.qty,0);$("#cartCount").textContent=n;$("#wishCount").textContent=state.wish.length}
function add(id){const i=state.cart.find(x=>x.id===id);i?i.qty++:state.cart.push({id,qty:1});save();toast("PRODUK DITAMBAHKAN KE KERANJANG")}
function wish(id){state.wish=state.wish.includes(id)?state.wish.filter(x=>x!==id):[...state.wish,id];save();renderHome();renderProducts();toast(state.wish.includes(id)?"DITAMBAHKAN KE WISHLIST":"DIHAPUS DARI WISHLIST")}
function renderCart(){const box=$("#cartItems");if(!state.cart.length){box.innerHTML=`<div class="form-card" style="margin:15px;text-align:center">KERANJANG KOSONG</div>`;$("#cartTotal").textContent=money(0);return}let total=0;box.innerHTML=state.cart.map(x=>{const p=state.products.find(p=>p.id===x.id);total+=p.price*x.qty;return `<div class="cart-row"><div class="cart-art">${p.art}</div><div><b>${p.name}</b><small>${money(p.price)} × ${x.qty}</small></div><button class="remove" data-remove="${p.id}">HAPUS</button></div>`}).join("");$("#cartTotal").textContent=money(total)}
function openCart(){renderCart();$("#cartDrawer").classList.add("open")}function closeCart(){$("#cartDrawer").classList.remove("open")}
function renderCheckout(){let total=0;$("#checkoutItems").innerHTML=state.cart.map(x=>{const p=state.products.find(p=>p.id===x.id);total+=p.price*x.qty;return `<div class="order-row"><span>${p.name} × ${x.qty}</span><b>${money(p.price*x.qty)}</b></div>`}).join("");$("#checkoutTotal").textContent=money(total)}
function openDetail(id){const p=state.products.find(x=>x.id===id);$("#detailContent").innerHTML=`<div class="detail-layout"><div class="detail-art">${p.art}</div><div><span class="eyebrow">${p.category}</span><h2>${p.name}</h2><div class="meta">★ ${p.rating} • ${p.sold.toLocaleString("id-ID")} TERJUAL</div><p>Produk digital REXX MARKET DIGITAL dengan proses order terstruktur. Setelah checkout, buyer mengisi data dan sistem membuat transaksi QRIS melalui Pakasir.</p><div class="price"><strong style="font-size:24px">${money(p.price)}</strong><span class="old">${money(p.oldPrice)}</span></div><button class="primary" style="margin-top:15px" data-detail-add="${p.id}">TAMBAH KE KERANJANG</button></div></div>`;$("#detailModal").classList.add("open")}
document.addEventListener("click",e=>{const a=e.target.closest("[data-add]");if(a){e.stopPropagation();add(a.dataset.add)}const w=e.target.closest("[data-wish]");if(w){e.stopPropagation();wish(w.dataset.wish)}const r=e.target.closest("[data-remove]");if(r){state.cart=state.cart.filter(x=>x.id!==r.dataset.remove);save()}const c=e.target.closest(".product-card");if(c&&!e.target.closest("button"))openDetail(c.dataset.id);const da=e.target.closest("[data-detail-add]");if(da){add(da.dataset.detailAdd);$("#detailModal").classList.remove("open");openCart()}});
$("#cartBtn").onclick=openCart;$("#closeCart").onclick=closeCart;$(".drawer-backdrop").onclick=closeCart;$("#closeDetail").onclick=()=>$("#detailModal").classList.remove("open");$(".modal-backdrop").onclick=()=>$("#detailModal").classList.remove("open");$("#wishBtn").onclick=()=>{state.search="";state.category="SEMUA";page("productsPage");$("#productsGrid").innerHTML=state.products.filter(p=>state.wish.includes(p.id)).map(card).join("")||`<div class="form-card" style="grid-column:1/-1;text-align:center">WISHLIST KOSONG</div>`};
$("#checkoutBtn").onclick=()=>{if(!state.cart.length)return toast("KERANJANG KOSONG");closeCart();page("checkoutPage")};
$("#sortSelect").onchange=renderProducts;
function search(){state.search=$("#searchInput").value.toLowerCase().trim();page("productsPage")}
$("#searchBtn").onclick=search;$("#searchInput").onkeydown=e=>{if(e.key==="Enter")search()};
$("#checkoutForm").onsubmit=async e=>{e.preventDefault();const btn=$("#payBtn"),err=$("#formError");err.textContent="";btn.disabled=true;btn.textContent="MEMPROSES...";try{const fd=new FormData(e.target);const buyer=Object.fromEntries(fd.entries());const r=await fetch("/api/orders",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({items:state.cart,buyer})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Gagal membuat order");state.orderId=d.orderId;$("#paymentOrderId").textContent=d.orderId;$("#paymentAmount").textContent=money(d.payment.totalPayment||d.amount);$("#paymentExpired").textContent=new Date(d.payment.expiredAt).toLocaleString("id-ID");$("#qrImage").src=d.payment.qrDataUrl;$("#qrFallback").textContent="";page("paymentPage");startPolling(d.orderId)}catch(x){err.textContent=x.message}finally{btn.disabled=false;btn.textContent="BUAT PESANAN & QRIS"}};
async function checkPayment(){if(!state.orderId)return;try{const r=await fetch("/api/orders-status?orderId="+encodeURIComponent(state.orderId));const d=await r.json();if(d.status==="completed"){clearInterval(state.poll);$("#paymentStatus").textContent="PEMBAYARAN BERHASIL";$("#paymentStatus").className="status success";state.cart=[];save();toast("PEMBAYARAN BERHASIL")}else if(d.status==="failed"||d.status==="cancelled"){clearInterval(state.poll);$("#paymentStatus").textContent="TRANSAKSI " + d.status.toUpperCase();$("#paymentStatus").className="status failed"}}catch{}}
function startPolling(id){state.orderId=id;clearInterval(state.poll);state.poll=setInterval(checkPayment,5000);checkPayment()}
$("#refreshPayment").onclick=checkPayment;
(async function init(){try{const r=await fetch("/api/store");const s=await r.json();$("#storeName").textContent=s.storeName;$("#storeTagline").textContent=s.tagline;$("#storeProfile").src=s.profileImage;$("#footerProfile").src=s.profileImage;$("#footerName").textContent=s.storeName;$("#contactText").textContent=s.adminContact;renderNav(s.categories)}catch{renderNav(["SEMUA","PANEL HOSTING","VPS","BOT HOSTING","SOFTWARE","VOUCHER"])}renderHome();renderProducts();updateCounts();renderCart()})();
